name: Films project CI

on:
  push:
    branches: [ level-1 ]
  pull_request:
    branches: [ level-1 ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: stop service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            pm2 kill
            rm ~/backend -r -f

      - name: make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_NODE_ENV: "production"
          envkey_PORT: 3333
          envkey_SECRET_KEY: ${{ secrets.JWT_SECRET }}

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: .
          target: ~/backend


      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/backend
            npm install
            pm2 start app.js
            sudo cp nginx.conf /etc/nginx/sites-available/default
            sudo systemctl restart nginx

      - name: the job failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} - возникли ошибки при выкатке проекта!


  send_message:
    name: Send message
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} - успешно выкачен!
